<?php

namespace App\Services;

use App\Models\AlokasiPembayaran;
use App\Models\Pembayaran;
use App\Models\Tagihan;

class WhatsAppTagihanService
{
    public function __construct(
        private WhatsAppService $whatsapp,
    ) {
    }

    /**
     * Return the exact WhatsApp action used by the web Tagihan button.
     * The message and URL are generated by the existing WhatsAppService.
     */
    public function forTagihan(Tagihan $tagihan): array
    {
        if ($tagihan->status === Tagihan::STATUS_LUNAS) {
            $pembayaran = $this->pembayaranUntukTagihan($tagihan);

            if ($pembayaran) {
                return [
                    'url' => $this->whatsapp->pembayaran($pembayaran),
                    'message' => $this->whatsapp->pesanPembayaran($pembayaran),
                ];
            }
        }

        return [
            'url' => $this->whatsapp->tagihan($tagihan),
            'message' => $this->whatsapp->pesanTagihanBaru($tagihan),
        ];
    }

    private function pembayaranUntukTagihan(Tagihan $tagihan): ?Pembayaran
    {
        $alokasi = AlokasiPembayaran::with('pembayaran')
            ->where('tagihan_id', $tagihan->id)
            ->whereHas('pembayaran', function ($query) {
                $query->where('status', Pembayaran::STATUS_BERHASIL);
            })
            ->latest('id')
            ->first();

        return $alokasi?->pembayaran;
    }
}
